logging:
  level:
    org.springframework: INFO
    org.sterl.filesync: DEBUG
sync:
  source: /Users/sterlp/dev/workspace
  destination: /Users/sterlp/dev/workspace_sync
  ignoreFiles:
    - .DS_Store
  maxChangeListenDepth: 8